# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f32cd8ac-76ae-418d-a860-06cba707831d";
      fsType = "ext4";
    };

  fileSystems."/boot/EFI" =
    { device = "/dev/disk/by-uuid/D608-6FD8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

# fileSystems."/windows" =
#   { device = "/dev/disk/by-uuid/ACAECEFEAECEBFD6";
#     fsType = "ntfs-3g";
#     options = [ "defaults" "rw" "umask=000" ];
#   };

#   fileSystems."/home/Samuel/gentoo-home" =
#    { device = "/dev/disk/by-uuid/f752fc0a-9f78-453a-a6c9-b37ad71cf77e";
#      fsType = "ext4";
#      options = [ "defaults" "rw" "umask=000" ];
#    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/45349c1c-216c-4f1d-ba22-27cc30e7a4ec"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
